// <auto-generated />
using System;
using APBD_Midterm2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Midterm2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250609093133_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Midterm2.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.MachineProgram", b =>
                {
                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramDefId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("WMId")
                        .HasColumnType("int");

                    b.HasKey("MachineId", "ProgramDefId");

                    b.HasIndex("ProgramDefId");

                    b.HasIndex("WMId");

                    b.ToTable("MachineProgram");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Program");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 69,
                            Name = "Quick Wash"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 143,
                            Name = "Cotton Cycle"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 100,
                            Name = "Synthetic"
                        });
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WashingMachineId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.PurchaseProgram", b =>
                {
                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId", "ProgramId");

                    b.HasIndex("ProgramId");

                    b.ToTable("PurchaseProgram");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.WashingMachine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Washing_Machine");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.MachineProgram", b =>
                {
                    b.HasOne("APBD_Midterm2.Models.Program", "Program")
                        .WithMany("MachinePrograms")
                        .HasForeignKey("ProgramDefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Midterm2.Models.WashingMachine", "WM")
                        .WithMany("MachinePrograms")
                        .HasForeignKey("WMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("WM");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Purchase", b =>
                {
                    b.HasOne("APBD_Midterm2.Models.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Midterm2.Models.WashingMachine", "WashingMachine")
                        .WithMany("Purchases")
                        .HasForeignKey("WashingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("WashingMachine");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.PurchaseProgram", b =>
                {
                    b.HasOne("APBD_Midterm2.Models.Program", "Program")
                        .WithMany("PurchasePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Midterm2.Models.Purchase", "Purchase")
                        .WithMany("PurchasePrograms")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Customer", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Program", b =>
                {
                    b.Navigation("MachinePrograms");

                    b.Navigation("PurchasePrograms");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.Purchase", b =>
                {
                    b.Navigation("PurchasePrograms");
                });

            modelBuilder.Entity("APBD_Midterm2.Models.WashingMachine", b =>
                {
                    b.Navigation("MachinePrograms");

                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
